server: #server config
#  servlet.context-path: /springbootdemo/api
#  port: 443
#  #Springboot配置使用ssl，使用https
#  #生成证书命令：keytool -genkey -alias tomcat -keyalg RSA -keystore D:/tomcat.keystore
#  ssl:
#  #你生成的证书名字
#    key-store: tomcat.keystore
#  #密钥库密码
#    key-store-password: 123456
#    keyStoreType: JKS
#    keyAlias: tomcat
  servlet.context-path: /springbootdemo
  port: 8888
spring:
  main: #spring boot config
    show-banner: false #关闭bannev
#  cache:
#    ehcache:
#      config: classpath:config/ehcache.xml
  datasource: #data source config
   type: com.alibaba.druid.pool.DruidDataSource
   driver-class-name: com.mysql.jdbc.Driver
   #开发环境
   url: jdbc:mysql://127.0.0.1:3306/springBoot?useUnicode=true&characterEncoding=utf-8&useSSL=false
   username: root
   password: 123456

   #initScriptFile: /sql/init.sql
   #max-wait-millis: 3600000
   validationQuery: SELECT 1 FROM DUAL
   testOnBorrow: true
   testWhileIdle: true
   timeBetweenEvictionRunsMillis: 60000
   transaction:
        rollback-on-commit-failure: true
   #配置rabbitmq连接
   rabbitmq:
       host: localhost
       port: 5672
       username: guest
       password: guest
       virtual-host: /
       # 轮询分发prefetch默认是1(公平分发），如果设置为0就是轮询模式
       listener:
         simple:
           prefetch: 0
   #    publisher-confirms: true
  #配置redis数据库连接
#   redis:
#     host: 127.0.0.1
#     port: 6379
#     pool:
#       max-idle: 20      # 连接池中的最大空闲连接
#       min-idle: 1
#       max-active: 20    # 连接池最大连接数（使用负值表示没有限制）
#       max-wait: 60000   #连接池最大阻塞等待时间
#     database: 0         #默认是索引为的0的数据库
  mail:
       host: smtp.qq.com
       username:  2823598901@qq.com
       password:  tibisqigydhydhee  #QQ邮箱的授权码（QQ邮箱->设置->账户->POP3/SMTP服务:开启服务后会获得QQ的授权码）
       properties:
          mail:
            smtp:
              default-encoding: UTF-8
              auth: true//这样才能通过验证
              starttls:
                  enable: true
                  required: true

  messages: #i18n config
    basename: i18n/messages
   
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    
  aop: #AOP config
    auto: true
    proxy-target-class: false
# spring-activiti
  #activiti:
    #自动部署验证设置:true-开启（默认）、false-关闭
    #check-process-definitions: false
    # asyncExecutorEnabled属性设置设置true后将代替那些老的Job executor
    #async-executor-enabled: false
    #job-executor-activate: false
  mybatis:
      type-aliases-package: com.kevin.model
      mapper-locations: classpath:com/kevin/dao/*/*.xml
#ROOT_PATH: /springbootdemo
ROOT_PATH: D:\idealWorkspace\projects\springbootdemo\src\main\resources
#html保存的上传地址
TEST_UPLOAD_HTML_URL: ${ROOT_PATH}/static/savehtml/
#html信息内容模板
TEST_HTML_TEMPLATE_URL: ${ROOT_PATH}/static/template/wx_template.html