server: #server config
  servlet.context-path: /springbootdemo
  port: 8080
spring:
  main: #spring boot config
    show-banner: false #关闭bannev
#  cache:
#    ehcache:
#      config: classpath:config/ehcache.xml
  datasource: #data source config
   type: com.alibaba.druid.pool.DruidDataSource
   driver-class-name: com.mysql.jdbc.Driver
   #开发环境
   url: jdbc:mysql://127.0.0.1:3306/springBoot?useUnicode=true&characterEncoding=utf-8&useSSL=false
   username: root
   password: 123456

   #initScriptFile: /sql/init.sql
   #max-wait-millis: 3600000
   validationQuery: SELECT 1 FROM DUAL
   testOnBorrow: true
   testWhileIdle: true
   timeBetweenEvictionRunsMillis: 60000
   #配置rabbitmq连接
   rabbitmq:
       host: localhost
       port: 5672
       username: guest
       password: guest
       virtual-host: /
       # 轮询分发prefetch默认是1(公平分发），如果设置为0就是轮询模式
       listener:
         simple:
           prefetch: 0
   #    publisher-confirms: true
  #配置redis数据库连接
#   redis:
#     host: 127.0.0.1
#     port: 6379
#     pool:
#       max-idle: 20      # 连接池中的最大空闲连接
#       min-idle: 1
#       max-active: 20    # 连接池最大连接数（使用负值表示没有限制）
#       max-wait: 60000   #连接池最大阻塞等待时间
#     database: 0         #默认是索引为的0的数据库
  mail:
       host: smtp.qq.com
       username:  2823598901@qq.com
       password:  tibisqigydhydhee  #QQ邮箱的授权码（QQ邮箱->设置->账户->POP3/SMTP服务:开启服务后会获得QQ的授权码）
       properties:
          mail:
            smtp:
              default-encoding: UTF-8
              auth: true//这样才能通过验证
              starttls:
                  enable: true
                  required: true

  messages: #i18n config
    basename: i18n/messages
   
  thymeleaf: #thymeleaf config
    mode: HTML5
    encoding: UTF-8
    spring.thymeleaf.servlet.content-type: text/html
    cache: false
    
  aop: #AOP config
    auto: true
    proxy-target-class: false
  activiti:
    check-process-definitions: false

  mybatis:
      type-aliases-package: com.kevin.model
      mapper-locations: classpath:com/kevin/dao/*/*.xml